site_name: Python Reference

theme:
  favicon: 'images/favicon.png'
  name: 'material'

  font: false

  palette:
    primary: 'brown'
    accent: 'purple'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# nav:
#   - variables.md
#   - functions.md
